apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: koa-frontend
  name: koa-frontend
spec:
  selector:
    matchLabels:
      app: koa-frontend
      version: v1
  template:
    metadata:
      labels:
        app: koa-frontend
        version: v1
    spec:
      containers:
      - image: gcr.io/hov90901/koa-frontend:207a010
        name: koa-frontend
        ports:
        - containerPort: 80
